[GLOBAL]
pants_version = "2.15.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",  
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

pants_ignore = [
  # default
  ".*/", "/dist/", "__pycache__",

  # ignore existing code
  "chain", "data", "examples", "strategy", "utils",
]

[test]
report = true

[mypy]
version = "mypy~=1.1.1"
lockfile = "mypy.lockfile"

args = ["--verbose", "--follow-imports", "silent"]

[pytest]
version = "pytest~=7.2.2"
lockfile = "pytest.lockfile"

xdist_enabled = true

extra_requirements = [
  "pytest-asyncio",
  "pytest-cov",
  "pytest-xdist",
]