[tool.yapf]
based_on_style = "google"
indent_width = 2
column_limit = 120
spaces_before_comment = 1

split_before_first_argument = true
split_complex_comprehension = true
split_before_expression_after_opening_paren = true
split_before_dict_set_generator = true

coalesce_brackets = true
dedent_closing_brackets = true
continuation_indent_width = 2


[[tool.mypy.overrides]]
module = [
  # grpc-stubs exists, but it's missing stuff (can't find AioRpcSupport) and
  # doesn't support aio yet. Instead, we'll just blanket ignore grpc because
  # it's easier.
  #
  # https://stackoverflow.com/a/72714514
  # https://github.com/shabbyrobe/grpc-stubs/issues/22
  "grpc.*",

  # injective-py doesn't export usable type definitions, so mypy barfs on check
  "pyinjective.*",
]
ignore_missing_imports = true
