# flake8: noqa
# isort: skip_file
# coding: utf-8

# flake8: noqa

"""
    Frontrunner Market Maker

    This is a first draft of the FR External Market Maker API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
# import ApiClient
# import models into sdk package
