# coding: utf-8

"""
    Frontrunner Market Maker

    This is a first draft of the FR External Market Maker API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.frontrunner_api import FrontrunnerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFrontrunnerApi(unittest.TestCase):
    """FrontrunnerApi unit test stubs"""

    def setUp(self):
        self.api = FrontrunnerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_leagues(self):
        """Test case for get_leagues

        Get Frontrunner Sports Leagues  # noqa: E501
        """
        pass

    def test_get_markets(self):
        """Test case for get_markets

        Get Frontrunner Markets  # noqa: E501
        """
        pass

    def test_get_props(self):
        """Test case for get_props

        Get Frontrunner Props  # noqa: E501
        """
        pass

    def test_get_sport_entities(self):
        """Test case for get_sport_entities

        Get list of Frontrunner SportEntity  # noqa: E501
        """
        pass

    def test_get_sport_events(self):
        """Test case for get_sport_events

        Get list of Frontrunner SportEvent  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
