# coding: utf-8

"""
    Frontrunner Market Maker

    This is a first draft of the FR External Market Maker API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.market import Market  # noqa: E501
from swagger_client.rest import ApiException


class TestMarket(unittest.TestCase):
    """Market unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMarket(self):
        """Test Market"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.market.Market()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
