# coding: utf-8

"""
    Frontrunner Market Maker

    This is a first draft of the FR External Market Maker API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.sport_entity import SportEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestSportEntity(unittest.TestCase):
    """SportEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSportEntity(self):
        """Test SportEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sport_entity.SportEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
