# flake8: noqa
# isort: skip_file
# coding: utf-8

"""
    Frontrunner Market Maker

    This is a first draft of the FR External Market Maker API  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class League(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'LeagueId',
        'name': 'LeagueName',
        'updated': 'datetime',
        'sport': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'updated': 'updated',
        'sport': 'sport'
    }

    def __init__(self, id=None, name=None, updated=None, sport=None):  # noqa: E501
        """League - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._updated = None
        self._sport = None
        self.discriminator = None
        self.id = id
        self.name = name
        if updated is not None:
            self.updated = updated
        if sport is not None:
            self.sport = sport

    @property
    def id(self):
        """Gets the id of this League.  # noqa: E501


        :return: The id of this League.  # noqa: E501
        :rtype: LeagueId
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this League.


        :param id: The id of this League.  # noqa: E501
        :type: LeagueId
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this League.  # noqa: E501


        :return: The name of this League.  # noqa: E501
        :rtype: LeagueName
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this League.


        :param name: The name of this League.  # noqa: E501
        :type: LeagueName
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def updated(self):
        """Gets the updated of this League.  # noqa: E501


        :return: The updated of this League.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this League.


        :param updated: The updated of this League.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    @property
    def sport(self):
        """Gets the sport of this League.  # noqa: E501


        :return: The sport of this League.  # noqa: E501
        :rtype: str
        """
        return self._sport

    @sport.setter
    def sport(self, sport):
        """Sets the sport of this League.


        :param sport: The sport of this League.  # noqa: E501
        :type: str
        """

        self._sport = sport

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(League, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, League):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
