# flake8: noqa
# isort: skip_file
# coding: utf-8

"""
    Frontrunner Market Maker

    This is a first draft of the FR External Market Maker API  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Prop(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'PropId',
        'league_id': 'LeagueId',
        'league_name': 'LeagueName',
        'name': 'PropName',
        'prop_type': 'PropType',
        'created': 'datetime',
        'updated': 'datetime',
        'sport_event_id': 'SportEventId',
        'sport_event_name': 'SportEventName',
        'sport_event_type': 'SportEventType'
    }

    attribute_map = {
        'id': 'id',
        'league_id': 'leagueId',
        'league_name': 'leagueName',
        'name': 'name',
        'prop_type': 'propType',
        'created': 'created',
        'updated': 'updated',
        'sport_event_id': 'sportEventId',
        'sport_event_name': 'sportEventName',
        'sport_event_type': 'sportEventType'
    }

    def __init__(self, id=None, league_id=None, league_name=None, name=None, prop_type=None, created=None, updated=None, sport_event_id=None, sport_event_name=None, sport_event_type=None):  # noqa: E501
        """Prop - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._league_id = None
        self._league_name = None
        self._name = None
        self._prop_type = None
        self._created = None
        self._updated = None
        self._sport_event_id = None
        self._sport_event_name = None
        self._sport_event_type = None
        self.discriminator = None
        self.id = id
        if league_id is not None:
            self.league_id = league_id
        if league_name is not None:
            self.league_name = league_name
        self.name = name
        if prop_type is not None:
            self.prop_type = prop_type
        if created is not None:
            self.created = created
        if updated is not None:
            self.updated = updated
        if sport_event_id is not None:
            self.sport_event_id = sport_event_id
        if sport_event_name is not None:
            self.sport_event_name = sport_event_name
        if sport_event_type is not None:
            self.sport_event_type = sport_event_type

    @property
    def id(self):
        """Gets the id of this Prop.  # noqa: E501


        :return: The id of this Prop.  # noqa: E501
        :rtype: PropId
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Prop.


        :param id: The id of this Prop.  # noqa: E501
        :type: PropId
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def league_id(self):
        """Gets the league_id of this Prop.  # noqa: E501


        :return: The league_id of this Prop.  # noqa: E501
        :rtype: LeagueId
        """
        return self._league_id

    @league_id.setter
    def league_id(self, league_id):
        """Sets the league_id of this Prop.


        :param league_id: The league_id of this Prop.  # noqa: E501
        :type: LeagueId
        """

        self._league_id = league_id

    @property
    def league_name(self):
        """Gets the league_name of this Prop.  # noqa: E501


        :return: The league_name of this Prop.  # noqa: E501
        :rtype: LeagueName
        """
        return self._league_name

    @league_name.setter
    def league_name(self, league_name):
        """Sets the league_name of this Prop.


        :param league_name: The league_name of this Prop.  # noqa: E501
        :type: LeagueName
        """

        self._league_name = league_name

    @property
    def name(self):
        """Gets the name of this Prop.  # noqa: E501


        :return: The name of this Prop.  # noqa: E501
        :rtype: PropName
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Prop.


        :param name: The name of this Prop.  # noqa: E501
        :type: PropName
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def prop_type(self):
        """Gets the prop_type of this Prop.  # noqa: E501


        :return: The prop_type of this Prop.  # noqa: E501
        :rtype: PropType
        """
        return self._prop_type

    @prop_type.setter
    def prop_type(self, prop_type):
        """Sets the prop_type of this Prop.


        :param prop_type: The prop_type of this Prop.  # noqa: E501
        :type: PropType
        """

        self._prop_type = prop_type

    @property
    def created(self):
        """Gets the created of this Prop.  # noqa: E501


        :return: The created of this Prop.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Prop.


        :param created: The created of this Prop.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def updated(self):
        """Gets the updated of this Prop.  # noqa: E501


        :return: The updated of this Prop.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this Prop.


        :param updated: The updated of this Prop.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    @property
    def sport_event_id(self):
        """Gets the sport_event_id of this Prop.  # noqa: E501


        :return: The sport_event_id of this Prop.  # noqa: E501
        :rtype: SportEventId
        """
        return self._sport_event_id

    @sport_event_id.setter
    def sport_event_id(self, sport_event_id):
        """Sets the sport_event_id of this Prop.


        :param sport_event_id: The sport_event_id of this Prop.  # noqa: E501
        :type: SportEventId
        """

        self._sport_event_id = sport_event_id

    @property
    def sport_event_name(self):
        """Gets the sport_event_name of this Prop.  # noqa: E501


        :return: The sport_event_name of this Prop.  # noqa: E501
        :rtype: SportEventName
        """
        return self._sport_event_name

    @sport_event_name.setter
    def sport_event_name(self, sport_event_name):
        """Sets the sport_event_name of this Prop.


        :param sport_event_name: The sport_event_name of this Prop.  # noqa: E501
        :type: SportEventName
        """

        self._sport_event_name = sport_event_name

    @property
    def sport_event_type(self):
        """Gets the sport_event_type of this Prop.  # noqa: E501


        :return: The sport_event_type of this Prop.  # noqa: E501
        :rtype: SportEventType
        """
        return self._sport_event_type

    @sport_event_type.setter
    def sport_event_type(self, sport_event_type):
        """Sets the sport_event_type of this Prop.


        :param sport_event_type: The sport_event_type of this Prop.  # noqa: E501
        :type: SportEventType
        """

        self._sport_event_type = sport_event_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Prop, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Prop):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
