# flake8: noqa
# isort: skip_file
# coding: utf-8

"""
    Frontrunner Market Maker

    This is a first draft of the FR External Market Maker API  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SportEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'abbreviation': 'str',
        'updated': 'datetime',
        'league_id': 'LeagueId',
        'league_name': 'LeagueName'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'abbreviation': 'abbreviation',
        'updated': 'updated',
        'league_id': 'leagueId',
        'league_name': 'leagueName'
    }

    def __init__(self, id=None, name=None, abbreviation=None, updated=None, league_id=None, league_name=None):  # noqa: E501
        """SportEntity - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._abbreviation = None
        self._updated = None
        self._league_id = None
        self._league_name = None
        self.discriminator = None
        self.id = id
        self.name = name
        if abbreviation is not None:
            self.abbreviation = abbreviation
        if updated is not None:
            self.updated = updated
        if league_id is not None:
            self.league_id = league_id
        if league_name is not None:
            self.league_name = league_name

    @property
    def id(self):
        """Gets the id of this SportEntity.  # noqa: E501


        :return: The id of this SportEntity.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SportEntity.


        :param id: The id of this SportEntity.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this SportEntity.  # noqa: E501


        :return: The name of this SportEntity.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SportEntity.


        :param name: The name of this SportEntity.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def abbreviation(self):
        """Gets the abbreviation of this SportEntity.  # noqa: E501

        The abbreviation used on the Frontrunner UI  # noqa: E501

        :return: The abbreviation of this SportEntity.  # noqa: E501
        :rtype: str
        """
        return self._abbreviation

    @abbreviation.setter
    def abbreviation(self, abbreviation):
        """Sets the abbreviation of this SportEntity.

        The abbreviation used on the Frontrunner UI  # noqa: E501

        :param abbreviation: The abbreviation of this SportEntity.  # noqa: E501
        :type: str
        """

        self._abbreviation = abbreviation

    @property
    def updated(self):
        """Gets the updated of this SportEntity.  # noqa: E501


        :return: The updated of this SportEntity.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this SportEntity.


        :param updated: The updated of this SportEntity.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    @property
    def league_id(self):
        """Gets the league_id of this SportEntity.  # noqa: E501


        :return: The league_id of this SportEntity.  # noqa: E501
        :rtype: LeagueId
        """
        return self._league_id

    @league_id.setter
    def league_id(self, league_id):
        """Sets the league_id of this SportEntity.


        :param league_id: The league_id of this SportEntity.  # noqa: E501
        :type: LeagueId
        """

        self._league_id = league_id

    @property
    def league_name(self):
        """Gets the league_name of this SportEntity.  # noqa: E501


        :return: The league_name of this SportEntity.  # noqa: E501
        :rtype: LeagueName
        """
        return self._league_name

    @league_name.setter
    def league_name(self, league_name):
        """Sets the league_name of this SportEntity.


        :param league_name: The league_name of this SportEntity.  # noqa: E501
        :type: LeagueName
        """

        self._league_name = league_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SportEntity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SportEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
