name: Build
run-name: Default
on: [push]

jobs:
  Placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files
        run: ls ${{ github.workspace }}
