name: Deploy
run-name: Deploy
on:
  push:
    branches: [master]

jobs:

  GitHub-Pages:
    runs-on: ubuntu-latest
    container: slatedocs/slate:v2.13.1
    permissions:
      contents: write
    steps:
      - name: Prerequisites
        run: |
          apt-get update
          apt-get install -y git rsync
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fixes conflict with branch protection
          # https://stackoverflow.com/a/63733988
          persist-credentials: false
      - name: Git Setup
        run: |
          repo_dir=$(pwd)

          # suppress "detected dubious ownership in repository" garbage
          git config --global --add safe.directory "${repo_dir}"

          commit_author_name=$(git log -n 1 --format="%an" HEAD)
          commit_author_email=$(git log -n 1 --format="%ae" HEAD)

          # need to configure user details manually
          git config --global user.name "${commit_author_name}"
          git config --global user.email "${commit_author_email}"
      - name: Slate Build
        run: |
          repo_dir=$(pwd)

          rsync \
            --recursive \
            --delete \
            docs/ \
            /srv/slate/source \
            ;

          cd /srv/slate
          ./slate.sh build
      - name: Git Push
        run: |
          commit_title=$(git log -n 1 --format="%s" HEAD)
          commit_hash=$(git log -n 1 --format="%H" HEAD)
          commit_message=$(cat <<EOF
          ${commit_title}

          generated from commit ${commit_hash}
          EOF
          )

          git fetch origin gh-pages
          git checkout gh-pages

          rsync \
            --recursive \
            --delete \
            --exclude=.git/ \
            --exclude=.gitignore \
            /srv/slate/build/ \
            . \
            ;

          git add .
          git commit --allow-empty --message "${commit_message}"
          git show --name-status
          git push
