name: Release
run-name: Release
on:
  release: [published]

jobs:

  PyPI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        - environment: pypi/test
          prerelease: true
        - environment: pypi/prod
          prerelease: false
    environment: ${{ matrix.environment }}
    if: github.event.release.prerelease == matrix.prerelease
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Version
        run: |
          echo ${{ github.ref_name }} | sed -e "s/^v//g" > VERSION
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Setup Pants
        uses: pantsbuild/actions/init-pants@main
        with:
          named-caches-hash: ${{ hashFiles('**/*.lockfile') }}
          setup-python-for-plugins: "true"
      - name: Publish
        run: |
          export PANTS_TWINE_CONFIG="${{ vars.PANTS_TWINE_CONFIG }}"
          export TWINE_PASSWORD="${{ secrets.TWINE_API_TOKEN }}"

          pants publish ::
